title: "Organelle Therapeutics Tracker"
description: "オルガネラ標的医薬（作用機序・治験・承認）を追うブログ"
url: https://nagimukae.github.io      # 例: https://<your-username>.github.io
baseurl: /organelle-therapeutics-tracker  # 例: /organelle-therapeutics  （ユーザー/プロジェクトによって調整）

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

locale: ja-JP
minimal_mistakes_skin: "mint"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

author:
  name: "向江 凪"
  avatar : /assets/images/logo-drug.svg
  bio: "細胞生物学を研究している博士学生です。薬学部を卒業してオルガネラについて研究している視点から、オルガネラを標的とした医薬品動向について解説します。"
  location: "Nagoya, Japan"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-globe"
      url: "https://nagimukae.com"
    - label: "X/Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/shike_cellbio?s=21&t=0eqzOOI41KCZPUY425cHpg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NagiMukae"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: true
      toc: true
      toc_sticky: true
      read_time: true
      share: true

paginate: 7
paginate_path: "/page:num/"
